<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use App\Models\Brand;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Obtener categorías y marcas
        $categories = Category::all()->keyBy('name');
        $brands = Brand::all()->keyBy('name');

        if ($categories->isEmpty() || $brands->isEmpty()) {
            $this->command->warn('Asegúrate de tener categorías y marcas creadas primero.');
            return;
        }

        $products = [
            // Bebidas
            [
                'name' => 'Coca Cola 2.5L',
                'sku' => 'BEB-COC-001',
                'description' => 'Refresco de cola 2.5 litros',
                'price' => 35.00,
                'weight' => '2.5L',
                'stock' => 50,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Bebidas',
                'brand' => 'Coca Cola',
            ],
            [
                'name' => 'Coca Cola 600ml',
                'sku' => 'BEB-COC-002',
                'description' => 'Refresco de cola personal',
                'price' => 15.00,
                'weight' => '600ml',
                'stock' => 100,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Bebidas',
                'brand' => 'Coca Cola',
            ],
            // Lácteos
            [
                'name' => 'Yogurt Lala Fresa',
                'sku' => 'LAC-LAL-001',
                'description' => 'Yogurt sabor fresa 1L',
                'price' => 28.00,
                'weight' => '1L',
                'stock' => 35,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Lácteos',
                'brand' => 'Lala',
            ],
            [
                'name' => 'Leche Lala Entera',
                'sku' => 'LAC-LAL-002',
                'description' => 'Leche entera 1L',
                'price' => 24.00,
                'weight' => '1L',
                'stock' => 40,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Lácteos',
                'brand' => 'Lala',
            ],
            // Pan Dulce
            [
                'name' => 'Pan Bimbo Blanco',
                'sku' => 'PAN-BIM-001',
                'description' => 'Pan de caja blanco grande',
                'price' => 42.00,
                'weight' => '680g',
                'stock' => 30,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Pan Dulce',
                'brand' => 'Bimbo',
            ],
            [
                'name' => 'Roles Bimbo',
                'sku' => 'PAN-BIM-002',
                'description' => 'Pan dulce con canela',
                'price' => 38.00,
                'weight' => '450g',
                'stock' => 25,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Pan Dulce',
                'brand' => 'Bimbo',
            ],
            // Limpieza
            [
                'name' => 'Cloro Multiusos 1L',
                'sku' => 'LIM-GEN-001',
                'description' => 'Blanqueador y desinfectante',
                'price' => 22.00,
                'weight' => '1L',
                'stock' => 45,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Limpieza',
                'brand' => 'Bimbo',
            ],
            [
                'name' => 'Papel Higiénico 4 rollos',
                'sku' => 'LIM-PAP-001',
                'description' => 'Papel higiénico doble hoja 4 rollos',
                'price' => 35.00,
                'weight' => '4 rollos',
                'stock' => 60,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Limpieza',
                'brand' => 'Bimbo',
            ],
            // Cuidado Personal
            [
                'name' => 'Jabón de Tocador',
                'sku' => 'CUI-JAB-001',
                'description' => 'Jabón antibacterial en barra',
                'price' => 12.00,
                'weight' => '100g',
                'stock' => 40,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Cuidado Personal',
                'brand' => 'Lala',
            ],
            // Botanas
            [
                'name' => 'Sabritas Adobadas',
                'sku' => 'BOT-SAB-001',
                'description' => 'Papas fritas sabor adobadas',
                'price' => 18.00,
                'weight' => '45g',
                'stock' => 80,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Botanas',
                'brand' => 'Sabritas',
            ],
            [
                'name' => 'Takis Fuego',
                'sku' => 'BOT-BAR-001',
                'description' => 'Totopos enrollados picantes',
                'price' => 16.00,
                'weight' => '62g',
                'stock' => 90,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Botanas',
                'brand' => 'Barcel',
            ],
            // Golosinas
            [
                'name' => 'Paleta Duvalin',
                'sku' => 'GOL-RIC-001',
                'description' => 'Dulce cremoso de avellana y vainilla',
                'price' => 8.00,
                'weight' => '18g',
                'stock' => 120,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Golosinas',
                'brand' => 'Ricolino',
            ],
            [
                'name' => 'Emperador Chocolate',
                'sku' => 'GOL-GAM-001',
                'description' => 'Galletas cubiertas de chocolate',
                'price' => 14.00,
                'weight' => '60g',
                'stock' => 70,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Golosinas',
                'brand' => 'Gamesa',
            ],
            // Abarrotes
            [
                'name' => 'Tostadas La Lupita',
                'sku' => 'ABA-LUP-001',
                'description' => 'Tostadas de maíz horneadas',
                'price' => 20.00,
                'weight' => '280g',
                'stock' => 55,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Abarrotes',
                'brand' => 'La Lupita',
            ],
            [
                'name' => 'Jamón FUD',
                'sku' => 'ABA-FUD-001',
                'description' => 'Jamón de pavo rebanado',
                'price' => 52.00,
                'weight' => '200g',
                'stock' => 20,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Abarrotes',
                'brand' => 'Fud',
            ],
            // Más Bebidas
            [
                'name' => 'Pepsi 2L',
                'sku' => 'BEB-PEP-001',
                'description' => 'Refresco de cola Pepsi 2 litros',
                'price' => 32.00,
                'weight' => '2L',
                'stock' => 45,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Bebidas',
                'brand' => 'Pepsi',
            ],
            [
                'name' => 'Coca Cola 355ml Lata',
                'sku' => 'BEB-COC-003',
                'description' => 'Refresco de cola en lata',
                'price' => 12.00,
                'weight' => '355ml',
                'stock' => 80,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Bebidas',
                'brand' => 'Coca Cola',
            ],
            [
                'name' => 'Agua Mineral 1.5L',
                'sku' => 'BEB-AGU-001',
                'description' => 'Agua purificada embotellada',
                'price' => 10.00,
                'weight' => '1.5L',
                'stock' => 100,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Bebidas',
                'brand' => 'Coca Cola',
            ],
            // Más Lácteos
            [
                'name' => 'Leche Carnation',
                'sku' => 'LAC-CAR-001',
                'description' => 'Leche evaporada Carnation',
                'price' => 18.00,
                'weight' => '360ml',
                'stock' => 50,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Lácteos',
                'brand' => 'Carnation',
            ],
            [
                'name' => 'Queso Lala',
                'sku' => 'LAC-LAL-003',
                'description' => 'Queso amarillo rebanado',
                'price' => 45.00,
                'weight' => '250g',
                'stock' => 30,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Lácteos',
                'brand' => 'Lala',
            ],
            // Enlatados
            [
                'name' => 'Chícharos Herdez',
                'sku' => 'ENL-HER-001',
                'description' => 'Chícharos en conserva',
                'price' => 15.00,
                'weight' => '215g',
                'stock' => 60,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Enlatados',
                'brand' => 'Herdez',
            ],
            [
                'name' => 'Frijoles La Sierra',
                'sku' => 'ENL-SIE-001',
                'description' => 'Frijoles refritos en lata',
                'price' => 18.00,
                'weight' => '430g',
                'stock' => 55,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Enlatados',
                'brand' => 'La Sierra',
            ],
            [
                'name' => 'Atún Herdez',
                'sku' => 'ENL-HER-002',
                'description' => 'Atún en agua',
                'price' => 22.00,
                'weight' => '140g',
                'stock' => 70,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Enlatados',
                'brand' => 'Herdez',
            ],
            [
                'name' => 'Elote Herdez',
                'sku' => 'ENL-HER-003',
                'description' => 'Granos de elote dulce',
                'price' => 16.00,
                'weight' => '220g',
                'stock' => 50,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Enlatados',
                'brand' => 'Herdez',
            ],
            // Más Botanas
            [
                'name' => 'Sabritas Clásicas',
                'sku' => 'BOT-SAB-002',
                'description' => 'Papas fritas saladas',
                'price' => 18.00,
                'weight' => '45g',
                'stock' => 75,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Botanas',
                'brand' => 'Sabritas',
            ],
            [
                'name' => 'Sabritas Jalapeño',
                'sku' => 'BOT-SAB-003',
                'description' => 'Papas fritas sabor jalapeño',
                'price' => 18.00,
                'weight' => '45g',
                'stock' => 70,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Botanas',
                'brand' => 'Sabritas',
            ],
            [
                'name' => 'Cheetos Poffs',
                'sku' => 'BOT-SAB-004',
                'description' => 'Botana de queso inflada',
                'price' => 16.00,
                'weight' => '42g',
                'stock' => 80,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Botanas',
                'brand' => 'Sabritas',
            ],
            [
                'name' => 'Ruffles Queso',
                'sku' => 'BOT-SAB-005',
                'description' => 'Papas onduladas sabor queso',
                'price' => 18.00,
                'weight' => '45g',
                'stock' => 65,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Botanas',
                'brand' => 'Sabritas',
            ],
            [
                'name' => 'Chips Jalapeño Barcel',
                'sku' => 'BOT-BAR-002',
                'description' => 'Papas fritas con jalapeño',
                'price' => 16.00,
                'weight' => '50g',
                'stock' => 70,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Botanas',
                'brand' => 'Barcel',
            ],
            // Más Galletas
            [
                'name' => 'Marías Gamesa',
                'sku' => 'GOL-GAM-002',
                'description' => 'Galletas Marías tradicionales',
                'price' => 12.00,
                'weight' => '190g',
                'stock' => 60,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Golosinas',
                'brand' => 'Gamesa',
            ],
            [
                'name' => 'Arcoiris Gamesa',
                'sku' => 'GOL-GAM-003',
                'description' => 'Galletas de animalitos con colores',
                'price' => 13.00,
                'weight' => '150g',
                'stock' => 55,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Golosinas',
                'brand' => 'Gamesa',
            ],
            [
                'name' => 'Chokis Marinela',
                'sku' => 'GOL-MAR-001',
                'description' => 'Galletas con chispas de chocolate',
                'price' => 15.00,
                'weight' => '128g',
                'stock' => 50,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Golosinas',
                'brand' => 'Marinela',
            ],
            [
                'name' => 'Principe Marinela',
                'sku' => 'GOL-MAR-002',
                'description' => 'Galletas de chocolate rellenas',
                'price' => 14.00,
                'weight' => '100g',
                'stock' => 60,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Golosinas',
                'brand' => 'Marinela',
            ],
            // Más Pan Dulce
            [
                'name' => 'Gansito Marinela',
                'sku' => 'PAN-MAR-001',
                'description' => 'Pastelito de chocolate con mermelada',
                'price' => 8.00,
                'weight' => '50g',
                'stock' => 100,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Pan Dulce',
                'brand' => 'Marinela',
            ],
            [
                'name' => 'Pingüinos Marinela',
                'sku' => 'PAN-MAR-002',
                'description' => 'Pastelito de chocolate relleno',
                'price' => 7.00,
                'weight' => '42g',
                'stock' => 90,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Pan Dulce',
                'brand' => 'Marinela',
            ],
            [
                'name' => 'Pan Bimbo Integral',
                'sku' => 'PAN-BIM-003',
                'description' => 'Pan de caja integral',
                'price' => 44.00,
                'weight' => '610g',
                'stock' => 25,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Pan Dulce',
                'brand' => 'Bimbo',
            ],
            // Abarrotes adicionales
            [
                'name' => 'Mayonesa McCormick',
                'sku' => 'ABA-MCC-001',
                'description' => 'Mayonesa con limón',
                'price' => 38.00,
                'weight' => '390g',
                'stock' => 40,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Abarrotes',
                'brand' => 'McCormick',
            ],
            [
                'name' => 'Salchicha FUD',
                'sku' => 'ABA-FUD-002',
                'description' => 'Salchichas de pavo',
                'price' => 48.00,
                'weight' => '250g',
                'stock' => 30,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Abarrotes',
                'brand' => 'Fud',
            ],
            [
                'name' => 'Aceite Vegetal',
                'sku' => 'ABA-ACE-001',
                'description' => 'Aceite vegetal para cocinar',
                'price' => 42.00,
                'weight' => '900ml',
                'stock' => 35,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Abarrotes',
                'brand' => 'Herdez',
            ],
            [
                'name' => 'Arroz 1kg',
                'sku' => 'ABA-ARR-001',
                'description' => 'Arroz blanco extra',
                'price' => 25.00,
                'weight' => '1kg',
                'stock' => 50,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Abarrotes',
                'brand' => 'La Sierra',
            ],
            // Más Golosinas
            [
                'name' => 'Carlos V',
                'sku' => 'GOL-RIC-002',
                'description' => 'Chocolate con cacahuate',
                'price' => 6.00,
                'weight' => '18g',
                'stock' => 100,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Golosinas',
                'brand' => 'Ricolino',
            ],
            [
                'name' => 'Lunetas',
                'sku' => 'GOL-RIC-003',
                'description' => 'Chocolates con leche',
                'price' => 10.00,
                'weight' => '35g',
                'stock' => 80,
                'is_active' => 1,
                'is_featured' => 0,
                'category' => 'Golosinas',
                'brand' => 'Ricolino',
            ],
            [
                'name' => 'Mazapán',
                'sku' => 'GOL-RIC-004',
                'description' => 'Dulce de cacahuate',
                'price' => 5.00,
                'weight' => '28g',
                'stock' => 110,
                'is_active' => 1,
                'is_featured' => 1,
                'category' => 'Golosinas',
                'brand' => 'Ricolino',
            ],
        ];

        foreach ($products as $productData) {
            $categoryName = $productData['category'];
            $brandName = $productData['brand'];
            unset($productData['category'], $productData['brand']);

            $category = $categories->get($categoryName);
            $brand = $brands->get($brandName);

            if ($category && $brand) {
                $productData['category_id'] = $category->id_category;
                $productData['brand_id'] = $brand->id_brand;
                Product::create($productData);
            }
        }

        $this->command->info('Productos de tienda de abarrotes creados exitosamente!');
    }
}
